#!/bin/sh

DAEMON=$(pwd)/aesdsocket

case "$1" in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -q -x $DAEMON -- -d
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -q -x $DAEMON
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0